### ISSUE TITLE
Some functionality won't work

### ISSUE THREAD

**Issue by ApexLegend007** [realme-kernel-opensource/realme_gt_master_exploratory_realme_Q5_Pro_GT-Neo3T-AndroidU-kernel-source#1]
As of Now, I have compiled the kernel successfully with the vendor source, but the sound on the speaker and sensors are dead on the RUI version "RMX3371_14.0.0.210(EX01)" in comparison to RUI version "RMX3371_14.0.0.140(EX01)"

**Comment by realme-kernel-opensource** [comment]
> As of Now, I have compiled the kernel successfully with the vendor source, but the sound on the speaker and sensors are dead on the RUI version "RMX3371_14.0.0.210(EX01)" in comparison to RUI version "RMX3371_14.0.0.140(EX01)"

Dear Customer,
For this issue, we need to capture logs for analysis. Please provide your email so that we can send you the method for capturing logs, or contact us through "realme-kernel-opensource@realme.com". Thank you.

**Comment by ApexLegend007** [comment]
> > As of Now, I have compiled the kernel successfully with the vendor source, but the sound on the speaker and sensors are dead on the RUI version "RMX3371_14.0.0.210(EX01)" in comparison to RUI version "RMX3371_14.0.0.140(EX01)"
> 
> 
> 
> Dear Customer,
> 
> For this issue, we need to capture logs for analysis. Please provide your email so that we can send you the method for capturing logs, or contact us through "realme-kernel-opensource@realme.com". Thank you.

Email me on :- siddhantmeena5@gmail.com

**Comment by ApexLegend007** [comment]
Sound is somehow got fixed after formatting data and sensor is still bugged
